import { useRef, useEffect } from 'react';
import Head from 'next/head';
import ComPDFKitViewer from '@compdfkit_pdf_sdk/webviewer';

export default function Home() {
  let docViewer = null;
  const viewer = useRef(null);

  useEffect(() => {
    ComPDFKitViewer.init({
      path: '/',
      pdfUrl: './example/developer_guide_web.pdf',
      license: 'qMP0vqPQwaQRzgpdsgT8XjiXImmg3wewcg4ZdhADT9+PImvelornERhjuXFmSm1u6vulW5hSW2Yl8JbNZVPfKYkWjYNnsFPdbF08Ki2XFXECyd+ioqSmR6QgXTzvjvsnYHAgHWlW1qaV3grt65gN3RTCPe32s3IAmZNyaXNJsFS6TbpO5Fz4Kha+hIC/0QKIY5f736R9Do368GJi1wsFtx3fpVqFSq1tE3/tEhm43GEom+y1Ea5sH8DJxSLa3uHndmmzPCDWhXNg+04zcDd7pRsFx/8QFm/IqOAp/SezG1QeZ3gZ2+CRt43iBqfeevPMbi3qtoX8IuN5HEOVGIDO6q8kD+Q9C95FZo3W7DLPF5IZWiBPIsFBXW6GG9jIMlEFWe5rnWo7I9ujPHSweIzq22orZsVxD5tPPZ5v7nNW86LvpYVrsZA1ZWyQ08PB4C5RojNrlBK+2jwgC76todX8+OMMXi5FZaHOhVK4mdgXvNKoU3I/BJTvpGOfrVXKJOP5Rm9A3ki7tGs3KS1+TcPxP+7hkxw+qkcPbbYUUZGSaFhWNmeZ8AxazlM2vWnAKDfxyB3zkYt10OmuUj4xx8hkvV5adbfllpJjvdp0DBYyOc6+K0TBVof+phlwhjszWrdm3QIveURmbR763QUBTybPikNm7rh2AHOlZwPY0qWudzuJdXp7Ua4M8Hk2hIUl5hSAyi0KfwVzaj4qZFJz98c3GhGqSEkBoRJBWuxkclY+4WlEQ+GYDjWpAryku2gWr457',
    }, viewer.current).then((instance) => {
      docViewer = instance.docViewer;
      docViewer.addEvent('documentloaded', async () => {
        console.log('ComPDFKit Web Demo loaded');
      })
    })
  }, []);

  return (
    <>
      <Head>
        <title>ComPDFKit Web Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="webviewer" ref={viewer} style={{ height: '100vh', overflow: 'hidden' }}></div>
    </>
  );
}
